/* ==============================================================*
 *  Lucky‑Moment  – 30 extra test users (idempotent)              *
 * ==============================================================*/

---------------- 0. bump sequences *only if they already exist* --
DO $$
DECLARE
    _seq text;
BEGIN
    FOREACH _seq IN ARRAY ARRAY[
        'users_id_seq',
        'profiles_id_seq',
        'photos_id_seq',
        'posts_id_seq',
        'user_settings_id_seq'
    ]
    LOOP
        IF EXISTS (SELECT 1 FROM pg_class WHERE relname = _seq) THEN
            EXECUTE format(
              'SELECT setval(%L, COALESCE((SELECT MAX(id)+1 FROM %I),1), FALSE);',
              _seq, replace(_seq,'_id_seq','')
            );
        END IF;
    END LOOP;
END$$;

---------------- 1. ensure 10 baseline interests ---------------
INSERT INTO interests (name) VALUES
 ('music'), ('sports'), ('art'), ('travel'), ('coding'),
 ('gaming'), ('reading'), ('fitness'), ('photography'), ('cooking')
ON CONFLICT (name) DO NOTHING;

---------------- 2. source data for 30 new users ---------------
WITH src(u,e) AS (
  VALUES
   ('alice2','alice2@example.com'), ('bob2','bob2@example.com'),
   ('carol','carol@example.com'),   ('dave2','dave2@example.com'),
   ('erin','erin@example.com'),     ('frank2','frank2@example.com'),
   ('grace2','grace2@example.com'), ('heidi2','heidi2@example.com'),
   ('ivan2','ivan2@example.com'),   ('judy2','judy2@example.com'),
   ('ken','ken@example.com'),       ('laura','laura@example.com'),
   ('mike','mike@example.com'),     ('nina','nina@example.com'),
   ('oscar','oscar@example.com'),   ('peggy','peggy@example.com'),
   ('quentin','quentin@example.com'),('ruth','ruth@example.com'),
   ('steve','steve@example.com'),   ('trudy','trudy@example.com'),
   ('ursula','ursula@example.com'), ('victor2','victor2@example.com'),
   ('wendy','wendy@example.com'),   ('xavier','xavier@example.com'),
   ('yolanda','yolanda@example.com'),('zed','zed@example.com'),
   ('amber2','amber2@example.com'), ('brad2','brad2@example.com'),
   ('carla2','carla2@example.com'), ('derek2','derek2@example.com')
),

---------------- 2‑A users --------------------------------------
new_users AS (
  INSERT INTO users (username,email,password_hash)
  SELECT u,e,'$2a$10$bxFZMt4M6IjHAKj6peP.wu6ps2TBA2RCoCoJCE..z/8oNJXJKJvTa' FROM src
  ON CONFLICT (email) DO NOTHING
  RETURNING id, username
),

---------------- 2‑B photos ------------------------------------
new_photos AS (
  INSERT INTO photos (url,description)
  SELECT 'https://example.com/avatars/'||username||'.jpg',
         username||' profile pic'
  FROM new_users
  RETURNING id,url
)

---------------- 2‑C profiles ----------------------------------
INSERT INTO profiles (
  user_id, display_name, biography, birthday, profile_picture_url,
  user_location_text, user_location,
  match_distance_miles, gender, preferred_gender,
  preferred_age_min, preferred_age_max, spotify_song_id
)
SELECT
  u.id,
  INITCAP(u.username),
  'Bio for '||u.username,
  DATE '1990-01-01' + (u.id*10) * INTERVAL '1 day',   -- ASCII hyphens
  p.url,
  'Denver, CO',
  ST_GeogFromText('SRID=4326;POINT(-104.99 39.74)'),
  100,'any','any',18,99,NULL
FROM new_users u
JOIN new_photos p ON TRUE
ON CONFLICT (user_id) DO NOTHING;

---------------- 2‑D settings ----------------------------------
INSERT INTO user_settings (user_id)
SELECT id
  FROM users
 WHERE username IN (
    'alice2','bob2','carol','dave2','erin','frank2',
    'grace2','heidi2','ivan2','judy2','ken','laura',
    'mike','nina','oscar','peggy','quentin','ruth',
    'steve','trudy','ursula','victor2','wendy','xavier',
    'yolanda','zed','amber2','brad2','carla2','derek2'
 )
ON CONFLICT DO NOTHING;

---------------- 2‑E posts (today + yesterday) ------------------
INSERT INTO posts(user_id,title,body,created_at)
SELECT id,
       'Hello from '||username,
       'Autogenerated post (today)',
       NOW()
  FROM users
 WHERE username IN (
   'alice2','bob2','carol','dave2','erin','frank2',
   'grace2','heidi2','ivan2','judy2','ken','laura',
   'mike','nina','oscar','peggy','quentin','ruth',
   'steve','trudy','ursula','victor2','wendy','xavier',
   'yolanda','zed','amber2','brad2','carla2','derek2'
 )
  AND NOT EXISTS (
    SELECT 1 FROM posts
     WHERE posts.user_id = users.id
       AND posts.title = 'Hello from '||users.username
  )

UNION ALL

SELECT id,
       'Yesterday''s note from '||username,
       'Autogenerated post (yesterday)',
       NOW() - INTERVAL '1 day'
  FROM users
 WHERE username IN (
   'alice2','bob2','carol','dave2','erin','frank2',
   'grace2','heidi2','ivan2','judy2','ken','laura',
   'mike','nina','oscar','peggy','quentin','ruth',
   'steve','trudy','ursula','victor2','wendy','xavier',
   'yolanda','zed','amber2','brad2','carla2','derek2'
 )
  AND NOT EXISTS (
    SELECT 1 FROM posts
     WHERE posts.user_id = users.id
       AND posts.title = 'Yesterday''s note from '||users.username
  )
;

---------------- 2‑F interests (3 each) -------------------------
INSERT INTO user_interests(user_id,interest_id)
SELECT u.id, ((row_number() OVER (ORDER BY u.id) - 1) % 10) + 1
  FROM users u
 WHERE u.username LIKE '%2'  -- all usernames ending in “2”
UNION ALL
SELECT u.id, ((row_number() OVER (ORDER BY u.id)    ) % 10) + 1
  FROM users u
 WHERE u.username LIKE '%2'
UNION ALL
SELECT u.id, ((row_number() OVER (ORDER BY u.id) + 1) % 10) + 1
  FROM users u
 WHERE u.username LIKE '%2'
ON CONFLICT DO NOTHING;

/*  done – 30 unique users created with posts, photos & interests */
